cabal-version: 1.12
name: thing-gen
version: 0.0.0
build-type: Simple

library
  exposed-modules:
      Thing.Gen
  hs-source-dirs:
      src
  build-depends:
      base
  default-language: Haskell2010

test-suite thing-test
  type: exitcode-stdio-1.0
  main-is: Main.hs
  other-modules:
      ThingChecks
  hs-source-dirs:
      test
  build-depends:
      base
  default-language: Haskell2010
